### ISSUE TITLE
rviz_imu_plugin make error

### ISSUE THREAD

**Issue by eemmyy23** [CCNYRoboticsLab/imu_tools#1]
Hi

When I am trying to install the plugin I get this error:
[ 25%] Building CXX object CMakeFiles/rviz_imu_plugin.dir/src/imu_display.o
  In file included from /home/emi/work_electric/rviz_imu_plugin/include/rviz_imu_plugin/imu_display.h:38:0,
                   from /home/emi/work_electric/rviz_imu_plugin/src/imu_display.cpp:31:
  /opt/ros/electric/stacks/visualization/rviz/src/rviz/visualization_manager.h:37:22: fatal error: wx/event.h: No such file or directory
  compilation terminated.
on Ubuntu 11.10 and ROS Electric

Can you give me a clue to solve this? 
Thank you

**Comment by idryanov** [comment]
On 05-Sep-12 11:35, eemmyy23 wrote:

> Hi
> 
> When I am trying to install the plugin I get this error:
> [ 25%] Building CXX object CMakeFiles/rviz_imu_plugin.dir/src/imu_display.o
> In file included from
> /home/emi/work_electric/rviz_imu_plugin/include/rviz_imu_plugin/imu_display.h:38:0,
> from /home/emi/work_electric/rviz_imu_plugin/src/imu_display.cpp:31:
> /opt/ros/electric/stacks/visualization/rviz/src/rviz/visualization_manager.h:37:22:
> fatal error: wx/event.h: No such file or directory
> compilation terminated.
> on Ubuntu 11.10 and ROS Electric
> 
> Can you give me a clue to solve this?
> Thank you
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ccny-ros-pkg/imu_tools/issues/1.

Hm. I haven't tested this on ROS Electric. It's quite possible the rviz 
plugin API changed between electric and fuerte.

I'll try it on my office machine, which still has Electric, and see what 
happens.

Cheers,
Ivan

**Comment by ChiaraTroiani** [comment]
Hi Guys!

any news for the rviz_imu_plugin in Electric ?

Thanks,
Cheers

Chiara

**Comment by ccny-ros-pkg** [comment]
I haven't had time to look at it, but most likely, the API changed between fuerte and electric. Also, it changed between fuerte and groovy. I might be able to port it for groovy, but I won't have time to port it to electric anytime soon

**Comment by mintar** [comment]
Works on fuerte, groovy and hydro. Closing.
