### ISSUE TITLE
Not as accurate results 6 DoF IMU

### ISSUE THREAD

**Issue by kelogs** [CCNYRoboticsLab/imu_tools#105]
I have had the code stripped off of the ros part; added these methods for obtaining pitch and roll angles from the quats:

```
double ComplementaryFilter::getRoll() const
{
  return atan(2 * (q0_*q1_ + q2_*q3_) / (1 - 2 * (q1_*q1_ + q2_*q2_)));
}

double ComplementaryFilter::getPitch() const
{
  return asin(2 * (q0_*q2_ - q3_*q1_));
}

...

		pitch = compFilter.getPitch() * 180.0 / M_PI;
		roll = compFilter.getRoll() * 180.0 / M_PI;
```

Running the algorithm (complementary filter) with no other mods than above on a double precision enabled STM32 MCU.
The sensor I am using is similar to the Phidgets one (using +/-8g accel range, +/-250 dps gyro range, restricted both gyro and accel BW to around 100Hz) and an 1 kHz ODR (measured `dt` fed to the `update` method was 0.898 ms):
https://www.phidgets.com/?&prodid=32#3-Axis_Accelerometer
https://invensense.tdk.com/products/motion-tracking/6-axis/icm-42605/#product-documentation

After about 8+ minutes runtime with the board stationary on my work desk:

pitch angle:
p_min	double	-0.11822205871028962	
p_max	double	0.22439301493628172	

roll angle:
r_min	double	-0.11964973157641175	
r_max	double	0.1911207986102208

Problems: multiple, the first and foremost - not getting the advertised ~ 0.02-ish degree accuracy for pitch and roll. My understanding of the algorithm is quite basic, but, hopefully, with some help, it is going to be solid enough to make the required adjustments.

Thank you,
Catalin

**Comment by mintar** [comment]
The complementary filter is @robertogl 's work, so maybe he can answer this.

**Comment by robertogl** [comment]
This could be anything, probably just vibrations on a not flat desk. I am closing this.
