### ISSUE TITLE
installing on debian

### ISSUE THREAD

**Issue by robert-meiner** [CCNYRoboticsLab/imu_tools#115]
For anyone wishing to use this with debian packages, the setup requires a few more steps and has some dependencies that need to be satisfied, before the package will compile:

Set up and build your catkin workspace.

A dependency is bullet, which you can install from the debian repositories

```
sudo apt-get install libbullet-dev
```

Another depency is ros/geometry2. clone this into the src directory of your workspace:

```
cd /catkin_ws/src
git clone -b <your ros version branch> https://github.com/ros/geometry2.git
cd ..
catkin_make
```
clone imu_tools into your src directory and build with ```catkin_make_isolated```

```
cd src
git clone -b <your ros version branch> https://github.com/ccny-ros-pkg/imu_tools.git
cd ..
catkin_make_isolated
```
Best Regards,
Mark

**Comment by mintar** [comment]
There's an even easier way using rosdep:

```bash
cd src
git clone -b $ROS_DISTRO https://github.com/ccny-ros-pkg/imu_tools.git
cd ..
rosdep install --from-paths src -i -y --rosdistro $ROS_DISTRO
catkin_make
```

For full details, see the Dockerfile: https://github.com/ccny-ros-pkg/imu_tools/blob/398f1ca293026894238e1aace80bf6fbfa26aafb/Dockerfile-melodic

This method *should* work on any other ROS package as well, provided they correctly specified their dependencies in the `package.xml` file.
