### ISSUE TITLE
ROS2 Madgwick Mag Bias Range

### ISSUE THREAD

**Issue by moormob** [CCNYRoboticsLab/imu_tools#118]
Madgwick for Eloquent does not allow typical values for magnetic bias (accepted values -10 to 10 with 0.01 resolution), however magnetic field msg uses Tesla units with typical values 1E-5. [http://docs.ros.org/api/sensor_msgs/html/msg/MagneticField.html](url)

Reason seems to be here: [https://github.com/ccny-ros-pkg/imu_tools/blob/835cb4f718d43612b46bb9e89cb2ea1f823236b5/imu_filter_madgwick/src/imu_filter_ros.cpp#L107](url)

Error message
`what():  parameter 'mag_bias_x' could not be set: Parameter {mag_bias_x} doesn't comply with floating point range.`

**Comment by mintar** [comment]
Fixed by #122.
