### ISSUE TITLE
Node publishing TF with very large timestemp

### ISSUE THREAD

**Issue by imkishan96** [CCNYRoboticsLab/imu_tools#131]
I am trying to use Imu filter (madgwick / complementary ) with intel realsense camera to get camera orientation in global frame.

but there is an error in rviz saying `Message removed because it is too old` . upon investigation; I realize ImuFilter node is publishing TF with very large time stemp(3212748723). 

tried to used static as well as dynamic TF from realsense camera but same results.

it would work randomy with correct timestemp 1 out of 15/20 tries.

I also tried `use_sim_time`  set it to `true` , which let it display on rviz and with correct timestemp but rest of code breaks down because of that , so I don't want to use it.

![Screenshot from 2020-11-26 01-49-50](https://user-images.githubusercontent.com/49663093/100322630-2b194200-2f8a-11eb-9a9a-bda0753dee04.png)

![Screenshot from 2020-11-26 01-09-04](https://user-images.githubusercontent.com/49663093/100322586-1b99f900-2f8a-11eb-871c-ef14ebbcc7ab.png)

![Screenshot from 2020-11-26 01-10-55](https://user-images.githubusercontent.com/49663093/100324413-d4f9ce00-2f8c-11eb-8ae8-e69dbe414ab8.png)

![Screenshot from 2020-11-26 02-07-14](https://user-images.githubusercontent.com/49663093/100324430-dc20dc00-2f8c-11eb-99f9-d691e88645d9.png)

**Comment by mintar** [comment]
Some tips:

* Make sure that you are using one of the more current branches (`kinetic`/`melodic`/`noetic`), not `indigo`.
* Setting the parameter `publish_tf` to `true` is mostly useful for debugging; usually, the IMU filter only publishes a `sensor_msgs/Imu` message, and that is then processed by a state estimator such as `robot_localization` to publish a TF.
* How to properly use simulation time:
  - If you are running on live data: `rosparam set use_sim_time false`
  - If you are running on recorded data from a bagfile:
      + `rosparam set use_sim_time false` before starting any nodes
      + start the IMU filter node
      + `rosbag play --clock <your-bagfile.bag>`
