### ISSUE TITLE
WARNING: The CMakeLists.txt of the metapackage 'imu_tools' contains non standard content. Use the content of the following file instead: /home/lyd/imu_catkin_ws/build/catkin_generated/metapackages/imu_tools/CMakeLists.txt

### ISSUE THREAD

**Issue by nuaalyd** [CCNYRoboticsLab/imu_tools#135]
You should remove the folder "imu_tools" before catkin_make, otherwise an error will occur like this:

`CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkin_workspace.cmake:100 (message):
  This workspace contains non-catkin packages in it, and catkin cannot build  a non-homogeneous workspace without isolation.  Try the  'catkin_make_isolated' command instead.`

And I wonder if anyone has such a problem.

**Comment by mintar** [comment]
You're probably on the "indigo" branch, which is *really* old. Switch to the "kinetic" branch instead.

**Comment by numb0824** [comment]
i have met the same problem,what should i do to solve this problem

**Comment by numb0824** [comment]
and my branch is melodic

**Comment by mintar** [comment]
Ok, I've fixed it in 32fac84b. Please pull the newest version of the `melodic` branch to fix this error.
