### ISSUE TITLE
Port to ROS2 foxy

### ISSUE THREAD

**Issue by cocodmdr** [CCNYRoboticsLab/imu_tools#139]
Hello,

Is there a way to use this package especially rviz_imu_plugin in ROS2 foxy ?

Thanks a lot !

**Comment by mintar** [comment]
Yes, the ROS2 version of this package is on the `eloquent` branch: https://github.com/ccny-ros-pkg/imu_tools/tree/eloquent

I haven't tested it with ROS2 Foxy, but with some luck it should work out of the box. Please report any issues you might have.
