### ISSUE TITLE
There is something wrong with kinetic branch.

### ISSUE THREAD

**Issue by nuaalyd** [CCNYRoboticsLab/imu_tools#143]
I found there is something wrong with kinetic branch when I follow the instruction"git clone -b noetic https://github.com/ccny-ros-pkg/imu_tools.git" and then "catkin_make", It reports an error like this:
`CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkin_workspace.cmake:100 (message):
  This workspace contains non-catkin packages in it, and catkin cannot build
  a non-homogeneous workspace without isolation.  Try the
  'catkin_make_isolated' command instead.
Call Stack (most recent call first):
  CMakeLists.txt:69 (catkin_workspace)`
then I clone the noetic branch and catkin_make, it works (I test it in ros kinetic with ubuntu 16.04).
I suspect some of the files are wrong in  kinetic branch. For example, the Launch file is missing under the imu_filter_magdwick package, which is present in the neotic branch.

**Comment by mintar** [comment]
I've tried to reproduce this, but everything works. There is nothing wrong with the `kinetic` branch.
