### ISSUE TITLE
how to get the orientation from IMU reading?

### ISSUE THREAD

**Issue by BojanAndonovski71** [CCNYRoboticsLab/imu_tools#144]
Hi Im doing some UUV simulation in gazebo and have IMU that gives me 9DOF namely my IMU data is like this 

> Cheader: 
>   seq: 301770
>   stamp: 
>     secs: 6064
>     nsecs: 844000000
>   frame_id: "thrbot/imu_link"
> orientation: 
>   x: 0.018933040808
>   y: -0.00209639450915
>   z: 0.337785931366
>   w: -0.941030185311
> orientation_covariance: [0.0001, 0.0, 0.0, 0.0, 0.0001, 0.0, 0.0, 0.0, 0.0001]
> angular_velocity: 
>   x: -8.94731200724e-05
>   y: 0.000117146098958
>   z: 7.81746250685e-06
> angular_velocity_covariance: [1.1519236000000001e-07, 0.0, 0.0, 0.0, 1.1519236000000001e-07, 0.0, 0.0, 0.0, 1.1519236000000001e-07]
> linear_acceleration: 
>   x: 0.0865246576615
>   y: -0.363323777859
>   z: 9.79281330072
> linear_acceleration_covariance: [1.6e-05, 0.0, 0.0, 0.0, 1.6e-05, 0.0, 0.0, 0.0, 1.6e-05]

I would like to get the orientation from the sensor readings with the filter ? how to use the launch file and the node?

**Comment by mintar** [comment]
It looks like your data already contains an orientation. If you'd still like to use this package to do a new estimation of the orientation using the angular velocity and linear acceleration fields, please have a look at [the README](https://github.com/ccny-ros-pkg/imu_tools) and the [wiki page](http://wiki.ros.org/imu_tools).
