### ISSUE TITLE
filters without magnetometer but with dual GPS heading

### ISSUE THREAD

**Issue by elgarbe** [CCNYRoboticsLab/imu_tools#149]
Is it possible to run madgwick or complimentary filter using dual GPS heading instead of magnetometer for yaw correction?

**Comment by mintar** [comment]
No, the filters in this package are for fusing accelerometer/gyroscope/magnetometer data only. You should probably run the filters here and then run [robot_localization](https://github.com/cra-ros-pkg/robot_localization) on top to fuse the output of this package with the dual GPS heading.

**Comment by elgarbe** [comment]
Oh,that's ok. What kind of message do I need to assemble with gps heading in order to fuse it on RL?
I know that it's not an IMU tools related question, but maybe you just have the answer.
Thanks

**Comment by mintar** [comment]
Sorry, I don't have the answer from the top of my head. Please look at the `robot_localization` documentation. If you have any questions, please ask on [https://answers.ros.org/](https://answers.ros.org/).

**Comment by robertogl** [comment]
An idea could be processing the GPS to calculate the yaw value and then convert it into a quaternion for publishing it. I think the quaternion representing only the yaw could be somehow used for correcting the prediction.
