### ISSUE TITLE
E: Unable to locate package ros-foxy-imu-tools

### ISSUE THREAD

**Issue by robertokcanale** [CCNYRoboticsLab/imu_tools#157]
The following command:

_**sudo apt-get install ros-foxy-imu-tools**_

Gives me this error
_E: Unable to locate package ros-foxy-imu-tools_

**Comment by mintar** [comment]
I just released this package into foxy 10 days ago: https://github.com/CCNYRoboticsLab/imu_tools/issues/154#issuecomment-1102502389

It will be available after the next Foxy sync. I don't know when that will happen; all we can do is wait. When the sync happens, it will be announced here:

* https://discourse.ros.org/tags/c/release/foxy/65/release
* https://discourse.ros.org/search?expanded=true&q=%23general%20tags%3Afoxy%2Brelease
