### ISSUE TITLE
Feature Request - Make input topics configurable

### ISSUE THREAD

**Issue by nakai-omer** [CCNYRoboticsLab/imu_tools#166]
Hello,

It will be very helpful if the input topics will cofigurable, to allow more flexibility, without have to remap existing imu driver's topics, or having to publish to non namespaces topics.

**Comment by mintar** [comment]
In my opinion, it's much better to use the built-in remap functionality of ROS instead of adding a parameter for the topic names to achieve the same goal. You don't need to remap the IMU driver's topics, you can remap the IMU filter topics instead.

**Comment by nakai-omer** [comment]
Ok thanks!
