### ISSUE TITLE
Enhancement: Configurable imu_frame name

### ISSUE THREAD

**Issue by aamirhatim** [CCNYRoboticsLab/imu_tools#167]
It would be nice to have a rosparam for the `imu_frame_` variable so that we can change the frame name if desired. If no alternative is provided, the code would just use the supplied frame id (current behavior).

**Comment by mintar** [comment]
So you mean the input data already has the wrong `frame_id`? In that case I believe it's much better to fix the problem at the source (i.e., add the `imu_frame` parameter to the IMU driver that's publishing the data) instead of fixing it downstream in this package.

**Comment by aamirhatim** [comment]
Good point. I've already started looking into the source publisher. Thanks Martin
