### ISSUE TITLE
Estimate diverges under constant input

### ISSUE THREAD

**Issue by tomas-c** [CCNYRoboticsLab/imu_tools#17]
I noticed that it drifted a lot with my IMU so I did a simple test.

I supplied (0,0,0) for angular velocity, (0, 0, 9.81) for linear acceleration and (-0.420,+0.302, 0.835) for magnetic vector. The resulting orientation (I looked at Euler angles) was very noisy and didn't converge (picture below). 
![original_code](https://f.cloud.github.com/assets/5213953/1509832/42ec824a-4a66-11e3-8f06-ec576a87e000.png)

If, however, the original code is used (I just replaced ImuFilter::madgwickAHRSupdate with Update function from https://github.com/xioTechnologies/Open-Source-AHRS-With-x-IMU/blob/master/x-IMU%20IMU%20and%20AHRS%20Algorithms/x-IMU%20IMU%20and%20AHRS%20Algorithms/AHRS/MadgwickAHRS.cs) the output is very smooth and converges quickly (picture below).
![modified_code](https://f.cloud.github.com/assets/5213953/1509833/56d2870a-4a66-11e3-9a38-62bbd2718cbd.png)

I suspect that a mistake was made while copying the original Madwick's code (something as silly as q1 instead of q2 could cause this).

**Comment by mintar** [comment]
This really looks like a bug. Can you upload that test code somewhere?

**Comment by tomas-c** [comment]
http://s.tomui.lt/failai/imu_test.zip

just run:

roslaunch imu_test test.launch

You can also find imu_filter-modified.cpp file in there which produces the results seen in the second picture.

**Comment by mintar** [comment]
I've narrowed it down to the three uses of `invSqrt()` instead of `1 / sqrt()`. I'll investigate further tomorrow.

**Comment by mintar** [comment]
The pull request above solves the problem. Thanks again for your great bug report + test code!

As a side node, I never had much luck using the magnetometer (it caused a lot of drag), so I just disable it and use the filter without it.
