### ISSUE TITLE
remove master branch

### ISSUE THREAD

**Issue by mintar** [CCNYRoboticsLab/imu_tools#18]
Hi @idryanov , could you please change the default branch from "master" to something else, like hydro, for example (Settings -> Default Branch)? I don't have the permissions to do that.

This would allow me to delete the `master` branch. It's only an (often outdated) alias of `fuerte` anyway, and many people don't realize that, so they are using the wrong branch for groovy/hydro.

**Comment by mikepurvis** [comment]
@idryanov Would be great to move forward with getting rid of the master branch, or at least making `indigo-devel` the default. It's pretty confusing the way it is.

**Comment by idryanov** [comment]
I don't mind any of these changes. Do you guys not have access to change the branches?

**Comment by idryanov** [comment]
Changed to indigo. Let me know if this works. I can try to figure out how to give you more permissions, since you are administrating most of the repo at the moment.

**Comment by mintar** [comment]
I don't think this worked as expected. The default seems to be `hydro`, and I can still see the `master` branch.

If you want to give me more permissions, I would be very grateful! The easiest way is to go to "Settings -> Collaborators -> Owners" and add my user name (@mintar) there.

**Comment by mintar** [comment]
Oh, wait a second. I think adding me to "Owners" would give me access to all the `ccny-ros-pkg` repos, which isn't necessary. So I guess you have to add a new team (e.g. "imu_tools_maintainers") with permissions set to "admin access" and add my user name to it. Then you can add that team to this repo from the "Settings -> Collaborators -> Owners" interface.

**Comment by mikepurvis** [comment]
The default is `indigo` for me now, yay.

@mintar You can remove the master branch by pushing nothing to it:

```
git push origin :master
```

**Comment by mintar** [comment]
> The default is indigo for me now, yay.

Hmm, when I do a `git clone` into a new directory without specifying the branch, I still get `hydro`. But in the github web interface, `indigo` is the default. Interesting.

> git push origin :master

Done! I couldn't do that as long as it was the default branch.

I think we can close this issue; I'll just leave it open for now as a reminder for @idryanov to do the permissions thing.
