### ISSUE TITLE
Catkin Support / Missing Header 

### ISSUE THREAD

**Issue by kscottz** [CCNYRoboticsLab/imu_tools#21]
I was trying to make a catkin package for this library. Would one currently exist or is it in the works?

Also, as I was trying roll my own catkin conversion I also noticed that imu_filter.h includes  ImuFilterMadgwickConfig.h which doesn't seem to be included in the github repo. Could this perhaps be auto generated and I am missing something in the cmake magic?

Let me know if you could use a hand doing to conversion to catkin. I would be more than happy to help out or test the package.

**Comment by mintar** [comment]
Hi @kscottz, catkin support is available on the `groovy` and `hydro` branches. The `master` branch is just an alias of `fuerte` and should be removed in order not to confuse users (see #18).

The `ImuFilterMadgwickConfig.h` is related to [dynamic_reconfigure](http://wiki.ros.org/dynamic_reconfigure) and indeed auto-generated when you run `rosmake` (on ROS Fuerte) or `catkin_make` (on ROS Groovy/Hydro).

And thanks for offering to help out! :-)

Cheers,
Martin

**Comment by kscottz** [comment]
SO. MUCH. AWESOME. Didn't checkout the branches. Thanks for the help!

**Comment by kscottz** [comment]
You may want to set the hyrdro branch to be the default branch displayed by github. You can still keep all your branches but the latest and greatest will be visible when new users visit. It should keep idiots like me from filing tickets. =)
