### ISSUE TITLE
Use the MagneticField message rather than Vector3Stamped

### ISSUE THREAD

**Issue by mikepurvis** [CCNYRoboticsLab/imu_tools#22]
Or hey, use a shapeshifter and support both.

http://docs.ros.org/api/sensor_msgs/html/msg/MagneticField.html

**Comment by mintar** [comment]
+1 to this!

My suggestion would be to keep using Vector3Stamped by default for a while, but emit a warning that it's deprecated. Also add a parameter to use MagneticField instead. Then make that the default in Indigo. Never heard the term "shapeshifter" (neither has Google), but I can imagine what you mean.

I'm happy to accept pull requests on this! :-)

**Comment by mikepurvis** [comment]
Cool, we'll look into it.

[ShapeShifter](http://docs.ros.org/hydro/api/topic_tools/html/classtopic__tools_1_1ShapeShifter.html) is part of topic_tools. It allows you to subscribe to a topic without specifying the type, and then react according to what you end up receiving. Doing it with a parameter is perhaps a little more obvious, though. :)

**Comment by mintar** [comment]
Ooh, shiny! I didn't know about ShapeShifter, looks very useful. But yeah, let's stick with a parameter here. (I don't like software that tries to outsmart the user...)

**Comment by mintar** [comment]
Closed via #43 .
