### ISSUE TITLE
Release to debs

### ISSUE THREAD

**Issue by mikepurvis** [CCNYRoboticsLab/imu_tools#23]
Consider moving to the ros-drivers org, as well?

**Comment by mintar** [comment]
+1 to releasing to debs. I'm too busy at the moment to look into that, though.

What would moving this repo to the ros-drivers organization entail? Any advantages/disadvantages? Although I've been unofficially maintaining this repo for about a year now, @idryanov is still the owner and original author, so I guess it's his call.

**Comment by idryanov** [comment]
I have no problem with transferring ownership, you guys have put
significant work into this

**Comment by mikepurvis** [comment]
Transferring the org signals a community intent to maintain it—it also means that if the maintainer happens to go AWOL, others can step in and be made admins on the repo without it having to move location.

Clearpath is in the early stages of considering deploying this code as part of a new product; we'd feel more comfortable not having a dependency on source outside the ros-\* repositories.

**Comment by mintar** [comment]
@idryanov: Thanks a lot! :-)

No problem from my point either. So how do we go about it? I guess somebody has to make me a member of the ros-drivers github organization so I can keep maintaining the repo. Where do I apply? :-)

I'd also like to transfer phidgets_drivers (if @idryanov is okay with that), since phidgets_drivers and imu_tools have been developed together and should stay together IMO.

**Comment by mikepurvis** [comment]
Make a [post on the sig](https://groups.google.com/forum/#!forum/ros-sig-drivers) with the proposal, and then use Github's repo settings page to initiate the transfer. You'll need repos created on ros-gbp as well, for creating releases.

I'm happy to help out with bloom stuff.

**Comment by mintar** [comment]
> Make a post on the sig with the proposal, and then use Github's repo settings page to initiate the transfer. 

Done!

> You'll need repos created on ros-gbp as well, for creating releases.

Not done yet.

> I'm happy to help out with bloom stuff.

Glad to hear!

**Comment by mikepurvis** [comment]
Did anything ever come of this? If we'd prefer not to move it to ros-perception over GPL concerns, I'd still like to create a release.

If you'd like, you could temporarily give me write access to this repo (and a release repo, probably `ccny-ros-pkg/imu_tools-release`) and I can do it, or happy to walk you through it. The process isn't too bad:

http://wiki.ros.org/bloom/Tutorials/FirstTimeRelease#bloom.2BAC8-Tutorials.2BAC8-PrepareUpstream.Preparing_the_Upstream_Repository

**Comment by mintar** [comment]
Yep, that's still on my radar. Will look into it ASAP. I can't give you write access, since I'm not an owner of this repo, but I think I'll manage the bloom stuff. :-)

**Comment by mintar** [comment]
Done: ros/rosdistro#6361

Sorry that it took me so long.

**Comment by mikepurvis** [comment]
Cool, thanks. Now that you've done that, we're totally going to hit you with a couple PRs and request a further release. :)

**Comment by mintar** [comment]
Looking forward to it! I promise I'll respond more quickly next time... :-)
