### ISSUE TITLE
Time step (dt) between consecutive samples

### ISSUE THREAD

**Issue by PaulKemppi** [CCNYRoboticsLab/imu_tools#3]
Hi,

I tried imu_filter_madgwick with Microstrain Imu (http://www.ros.org/wiki/microstrain_3dmgx2_imu), but ran into problems due to the time step estimation. Namely, in the filter, dt is calculated using the header time stamps available in the consecutive Imu input messages. The reality is (at least with my hardware - Lenovo X200 laptop, Intel Core Duo 2.4GHz running Ubuntu 12.04) that the time step between samples is not constant. Sometimes samples come in bursts from the sensor so multiple consecutive messages have exactly the same time stamp. This will ruin the dt calculation. Nevertheless, the sampling rate for sensor is known (100HZ) and on average, 100 messages are received every second.

So what I would suggest:
-dt could be ROS parameter for the filter node
-if dt is not set, it is estimated based on the time stamps as it is done now

Best Regards,
Paul Kemppi

**Comment by PaulKemppi** [comment]
Hi again,

I have now tested the imu_filter_madgwick both with Microstrain 3dm gx2 (without mag) and Xsens MTI-G (with/without mag). The filter seems to be working quite nicely after using a fixed dt. The rviz plugin for visualization is indeed very useful as well. Thanks for sharing the code! Next step is to study the method itself more carefully. I guess the same approach could be used to estimate relative altitude change (fusing barometric altimeter and vertical linear acceleration)?

Br,
Paul

**Comment by ccny-ros-pkg** [comment]
Thank you for the ticket.

I've added a parameter "constant_dt", measured in seconds, which defaults to 0.0. If left at 0.0, it will use the message timestamps to compute dt. If set to a positive value, it will use a constant dt. 

Let me know if this fixes the issue.

**Comment by PaulKemppi** [comment]
Hi,

Thanks for the update. It indeed fixes the issue.

-Paul
