### ISSUE TITLE
Seek for your help on IMU adaptor to Navigation.

### ISSUE THREAD

**Issue by asimay** [CCNYRoboticsLab/imu_tools#57]
hello, dear, I want to combine your module with "robot_localization" module and "Ros Navigation" module to work on my 4 wheels robot, is it possible or feasible?  I have some issues puzzled me.
1. how do i adapt the "robot_localization" module and "Ros Navigation" module ? I know I should pass the IMU filters result ---> robot_localization ---> Ros Navigation,  As to navigation module, which is it start entry node ? amcl or robot_pose_ekf ?
2. Is there any other good alternative or suggestion?  I think you must know the answer.

could you please give me some instructions on this? Thank you very much.

**Comment by mintar** [comment]
Dear @asimay , for this kind of questions, http://answers.ros.org/questions/ is much better suited than a GitHub issue. There are many more people there who can help you.
