### ISSUE TITLE
Cannot compile from source in OS X 10.12.1

### ISSUE THREAD

**Issue by toyoxx** [CCNYRoboticsLab/imu_tools#64]
Hi

I'm trying to compile imu_tools from source against ROS indigo on OS X (10.12.1, XCode 8.1). However, when compiling my workspace with catkin_make, I get [this errors](https://gist.github.com/toyoxx/470467b90d1691efd157900a9659258d)

I googled the error message, and everything pointed at `message_filters` not being added in the CMakeLists.txt or the package.xml. I checked, and even added it in the `rviz_imu_plugin` package (although I guess it's not necessary), but to no success.

I was wondering if you have any idea what might be causing this problem.

Thank you very much.

**Comment by mintar** [comment]
It looks like it's not linking against any of the ROS libraries or reading the headers correctly. I don't have a Mac to test with and no experience on compiling ROS on a Mac, so perhaps you're better off asking this question on http://answers.ros.org/ . Point out that you're trying to compile on a Mac, and perhaps people with experience in that area can help you.

> Undefined symbols for architecture x86_64:
>   "vtable for rviz::ImuDisplay", referenced from:
>       rviz::ImuDisplay::ImuDisplay() in imu_display.cpp.o
>       rviz::ImuDisplay::~ImuDisplay() in imu_display.cpp.o
> NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.

That one is weird. `rviz::ImuDisplay::ImuDisplay()` and `...::~ImuDisplay()` are defined right there in `imu_display.cpp`, so I have no idea why it's an undefined symbol. 

If you figure out how to fix compilation on a Mac, I'd be happy to accept pull requests! :)
