### ISSUE TITLE
rviz_imu_plugin

### ISSUE THREAD

**Issue by caoxudong0513** [CCNYRoboticsLab/imu_tools#68]
how can i use rviz_imu_plugin to display my mpu6050?
and i did this way https://github.com/lligen/myserial
can you help me ，please，thank you very much

**Comment by mintar** [comment]
Open RViz

- set "Fixed Frame" to the frame in your IMU messages, i.e. `imu_frame` in your case
- Add -> by display type -> rviz_imu_plugin -> Imu
- Topic: `/imu`
- check/uncheck "enable box", "enable axes", "enable arrow" however you like

BTW, by convention the topic shouldn't be called `imu`, but `imu/data`
