### ISSUE TITLE
imu rviz plugin crashes if orientation is not set.

### ISSUE THREAD

**Issue by chadrockey** [CCNYRoboticsLab/imu_tools#7]
I accidentally change the topic to an Imu without a fused orientation estimate.  This crashed RVIZ with the following error:

rviz: /tmp/buildd/ros-fuerte-visualization-common-1.8.4/debian/ros-fuerte-visualization-common/opt/ros/fuerte/stacks/visualization_common/ogre/build/ogre_src_v1-7-3/OgreMain/include/OgreAxisAlignedBox.h:252: void Ogre::AxisAlignedBox::setExtents(const Ogre::Vector3&, const Ogre::Vector3&): Assertion `(min.x <= max.x && min.y <= max.y && min.z <= max.z) && "The minimum corner of the box must be less than or equal to maximum corner"' failed.

You should probably catch the 0/0/0/0 orientation case and check orientation_covariance[0] < 0 before attempting to draw.

**Comment by mintar** [comment]
I juste tested this again, and couldn't reproduce any more (on Indigo/Trusty). I guess it got fixed at some point in the last 3,5 years... :)
