### ISSUE TITLE
What the orientation of sensor data should I set?

### ISSUE THREAD

**Issue by cc3t** [CCNYRoboticsLab/imu_tools#70]
In other word, what the axis orientation of earth coordinate frame for this novel algorithm?
I rewrote the complementary filter for MATLAB, but something is not right. I just wondering if the orientation of my sensor data is correct for the algorithm.
My sensor data coordinate like this:
http://rbwhitaker.wdfiles.com/local--files/3d-coordinate-systems/cartesian.png

**Comment by cc3t** [comment]
I already solve the problem.

**Comment by ghost** [comment]
Could you please let me know what orientation you used, I am having a similar issue.
