### ISSUE TITLE
Source Code

### ISSUE THREAD

**Issue by Bobur-kobilov** [CCNYRoboticsLab/imu_tools#76]
Hello,
How can I find your proposed source code?

Thanks

**Comment by mintar** [comment]
I don't understand your question. Just clone this repository. Perhaps look at some git and GitHub tutorials.

http://lmgtfy.com/?q=github+tutorial

**Comment by Bobur-kobilov** [comment]
I saw your video on youtube where you compared three filter algorithms. One is your proposed filter. I want to know whether complementry filter soruce code in ur repos is the same as one you used on youtube as a proposed filer.
Thanks

**Comment by mintar** [comment]
That is @robertogl 's work, so maybe he can answer this.

**Comment by Bobur-kobilov** [comment]
could you tell me how  I can connect with him?

Thanks

**Comment by mintar** [comment]
He should already have received a notification of this issue via email.

**Comment by mintar** [comment]
It's the middle of the night in NYC now, so be patient. :)

**Comment by Bobur-kobilov** [comment]
Thank you sir:)

**Comment by robertogl** [comment]
Just woke up :).
Yes, the complementary filter of this repo is the one I used to make that video.

Roberto

**Comment by Bobur-kobilov** [comment]
@robertogl @mintar Thank you a lot! I implemented the source code and it is giving me quaternion values. But, once i rotate the sensor, it is taking around 10secs to give me stable quaternion values. Could you help me with this issue plz?

**Comment by robertogl** [comment]
It sounds like an interpolation error. Make sure your lerp and/or slerp formulas are correct. If that’s fine try to see which part is causing the slow convergence by disabling the correction first (to output only prediction) and then prediction. Basically, debug your code :).

**Comment by Bobur-kobilov** [comment]
@mintar @robertogl  Thank you! I did as you said and now covergence is fast. 
1. Sorry but I have another issue with magnetometer. it is not giving good yaw angle values when i rotate the sensor. But When I run the without **getMagCorrection** function, for while it is giving me correct yaw angles until i rotate.
2. How can I choose Acc_gain,Mag_gain and Bais_alpha? Do I have to tune them for my IMU sensor?
 Could you give more some instructions please? 
Thank you a lot!
