### ISSUE TITLE
imu complementary filter: 180degrees rotated yaw

### ISSUE THREAD

**Issue by dsptech** [CCNYRoboticsLab/imu_tools#78]
Hi,
I added the imu complementary filter (from indigo branch) to a my own library to process data (accelerometer, gyroscope and magnetometer) from a Invensense MPU9250. 
The library work well but the yaw angle has a 180 degrees rotation when compared to the Mahony filter previously used in the same library (the yaw angle seems to be referred to the Geographic South Pole).

By reading the "Roberto G. Valenti, Ivan Dryanovski and Jizhong Xiao" paper, I see that the magnetic correction assume positive values (x component) for vectors pointing the Geographic North Pole but the magnetomer provide negative values in a such situation, so I need to invert the sign of the magnetic field before processing it.
Is right a such affirmation ?
Thank you.

**Comment by mintar** [comment]
Another question for you, @robertogl . :)

**Comment by dsptech** [comment]
Hi,
please, ignore my previous message. I missed this sentence from the above paper (chapter 4):
" _First, we redefine the global coordinate frame G to be aligned with the magnetic north. Specifically, the global frame’s x-axis points in the same direction as the local magnetic field (the z-axis remains vertical)_".
I need to check better the reference frame.
Thank you.
