### ISSUE TITLE
Variance for complementary filter

### ISSUE THREAD

**Issue by maracuya-robotics** [CCNYRoboticsLab/imu_tools#79]
We have noticed that the variance/covariance matrix in messages sent by the complementary filter are unset (zero). A parameter to set a static variance similar to #41 would be enough probably.

**Comment by mintar** [comment]
Yep, I haven't gone through the trouble of porting every issue that has been fixed in imu_filter_madgwick over to imu_complementary_filter. Could you prepare a pull request along the lines of #41?

**Comment by mintar** [comment]
Added in #85.
