### ISSUE TITLE
No declination

### ISSUE THREAD

**Issue by pavloblindnology** [CCNYRoboticsLab/imu_tools#83]
As I see there is no magnetic declination adjustment.
What is the reason for this, or it's just smth waiting for its implementation?

**Comment by mintar** [comment]
Please check Section 3.4 of the original Madgwick paper: http://x-io.co.uk/res/doc/madgwick_internal_report.pdf

Quote: 

> Declination errors, those in the horizontal plane relative to the earth’s surface, cannot be corrected without an additional reference of heading.  Inclination errors, those in the vertical plane relative to the earth’s surface, may be compensated for as the accelerometer provides an additional measurement of the sensor’s attitude.

The inclination errors are corrected in the `compensateMagneticDistortion()` function.

Does that answer your question?

**Comment by pavloblindnology** [comment]
No, it doesn't.
I mean declination specified as an external parameter, which is then just added to the final yaw.

**Comment by mintar** [comment]
Ah, now I understand. Sounds like a reasonable addition. I'm happy to accept a pull request that implements this feature.

**Comment by mintar** [comment]
This seems to have been addressed in #121 for ROS2. Maybe worth backporting to ROS1.

**Comment by mintar** [comment]
Fixed by #121.
