### ISSUE TITLE
rviz_imu_plugin make failure in Groovy

### ISSUE THREAD

**Issue by sobotacm** [CCNYRoboticsLab/imu_tools#9]
On Ubuntu 11.10 and ROS Groovy. Getting 1 package failure when i rosmake imu_tools (because property_manager.h does not exist in the latest rviz package).

Output on terminal:
{---------------------------------------------------------------------
  [rosbuild] Building package rviz_imu_plugin
  -- Using CATKIN_DEVEL_PREFIX: /opt/ros/groovy/stacks/imu_tools/rviz_imu_plugin/build/devel
  -- Using CMAKE_PREFIX_PATH: /opt/ros/groovy
  -- This workspace overlays: /opt/ros/groovy
  -- Found gtest: gtests will be built
  -- catkin 0.5.63
  [rosbuild] Including /opt/ros/groovy/share/roscpp/rosbuild/roscpp.cmake
  [rosbuild] Including /opt/ros/groovy/share/rospy/rosbuild/rospy.cmake
  -- Configuring done
  -- Generating done
  CMake Warning:
    Manually-specified variables were not used by the project:

```
  CMAKE_TOOLCHAIN_FILE
```

  -- Build files have been written to: /opt/ros/groovy/stacks/imu_tools/rviz_imu_plugin/build
  cd build && make -j -l8
  make[1]: Entering directory `/opt/ros/groovy/stacks/imu_tools/rviz_imu_plugin/build'
  make[2]: Entering directory`/opt/ros/groovy/stacks/imu_tools/rviz_imu_plugin/build'
  make[3]: Entering directory `/opt/ros/groovy/stacks/imu_tools/rviz_imu_plugin/build'
  make[3]: Leaving directory`/opt/ros/groovy/stacks/imu_tools/rviz_imu_plugin/build'
  [  0%] Built target rospack_genmsg_libexe
  make[3]: Entering directory `/opt/ros/groovy/stacks/imu_tools/rviz_imu_plugin/build'
  make[3]: Leaving directory`/opt/ros/groovy/stacks/imu_tools/rviz_imu_plugin/build'
  [  0%] Built target rosbuild_precompile
  make[3]: Entering directory `/opt/ros/groovy/stacks/imu_tools/rviz_imu_plugin/build'
  make[3]: Leaving directory`/opt/ros/groovy/stacks/imu_tools/rviz_imu_plugin/build'
  make[3]: Entering directory `/opt/ros/groovy/stacks/imu_tools/rviz_imu_plugin/build'
  [ 25%] Building CXX object CMakeFiles/rviz_imu_plugin.dir/src/imu_display.cpp.o
  In file included from /opt/ros/groovy/stacks/imu_tools/rviz_imu_plugin/src/imu_display.cpp:31:0:
  /opt/ros/groovy/stacks/imu_tools/rviz_imu_plugin/include/rviz_imu_plugin/imu_display.h:40:46: fatal error: rviz/properties/property_manager.h: No such file or directory
  compilation terminated.
  make[3]: *** [CMakeFiles/rviz_imu_plugin.dir/src/imu_display.cpp.o] Error 1
  make[3]: Leaving directory`/opt/ros/groovy/stacks/imu_tools/rviz_imu_plugin/build'
  make[2]: **\* [CMakeFiles/rviz_imu_plugin.dir/all] Error 2
  make[2]: Leaving directory `/opt/ros/groovy/stacks/imu_tools/rviz_imu_plugin/build'
  make[1]: *** [all] Error 2
  make[1]: Leaving directory`/opt/ros/groovy/stacks/imu_tools/rviz_imu_plugin/build'
-------------------------------------------------------------------------------}
[ rosmake ] Output from build of package rviz_imu_plugin written to:
[ rosmake ]    /root/.ros/rosmake/rosmake_output-20130312-225252/rviz_imu_plugin/build_output.log
[rosmake-2] Finished <<< rviz_imu_plugin [FAIL] [ 3.76 seconds ]  
[ rosmake ] Halting due to failure in package rviz_imu_plugin. 
[ rosmake ] Waiting for other threads to complete.
[ rosmake ] Results:  
[ rosmake ] Built 64 packages with 1 failures.  
[ rosmake ] Summary output to directory  
[ rosmake ] /root/.ros/rosmake/rosmake_output-20130312-225252

**Comment by fernandorocha** [comment]
I'm having the same issue.

**Comment by idryanov** [comment]
Thank you for the ticket.

Unfortunately the rviz addon system changed between fuerte and groovy. I haven't had the time to familiarize myself with the new one. Also, I probably won't have time to fix this in the near future. If someone wants to contribute, let me know and I can invite you as contributor.

**Comment by mintar** [comment]
Fixed in 459e198113b632ff98fb571cb45456516b6e74be (branch `groovy`).
