### ISSUE TITLE
RViz crashes on failed assertion

### ISSUE THREAD

**Issue by nwotero** [CCNYRoboticsLab/imu_tools#96]
The IMU plugin crashes RViz on a failed assertion when enabling the acceleration display:

> rviz: /build/ogre-1.9-mqY1wq/ogre-1.9-1.9.0+dfsg1/OgreMain/src/OgreNode.cpp:385: virtual void Ogre::Node::setOrientation(const Ogre::Quaternion&): Assertion `!q.isNaN() && "Invalid orientation supplied as parameter"' failed.

This failure should be detected and shown to the user without bringing down the whole process.

**Comment by mintar** [comment]
I can't reproduce this. Can you provide a rosbag that shows this error?
