### ISSUE TITLE
Compiling madgwick fails

### ISSUE THREAD

**Issue by ArashJavan** [CCNYRoboticsLab/imu_tools#99]
unfortunately i get following error during build process:

My Env:
ROS: Melodic
OS: Ubuntu 18.04

```
Errors     << imu_filter_madgwick:make /home/pc-milux/catkin_ws/catkin_miomap/logs/imu_filter_madgwick/build.make.001.log                               
/home/pc-milux/catkin_ws/catkin_miomap/src/imu_tools/imu_filter_madgwick/src/imu_filter_nodelet.cpp:39:24: error: expected constructor, destructor, or type conversion before ‘(’ token
 PLUGINLIB_DECLARE_CLASS(imu_filter_madgwick, ImuFilterNodelet, ImuFilterNodelet, nodelet::Nodelet);
```
any idea what is going wrong?

Thanks
----- 
**Update**
I was using wrong branch! Everything works fine now!

**Comment by numb0824** [comment]
hi,i have met the same problem .My Env is "ubuntu18.04+ros-melodic".Please help me what should i do?

**Comment by mintar** [comment]
Please check out the `melodic` branch.
